"use client";
import { useMemo, useRef, useState } from "react";
import { jsPDF } from "jspdf";

const consentText = "Ich erkläre mich damit einverstanden, dass die von Chris Franz Design aufgenommenen Fotos für Portfolio, Website, Social Media (z.B. Instagram/Facebook), Ausstellungen und Eigenwerbung verwendet werden dürfen. Eine kommerzielle Weitergabe an Dritte erfolgt nur nach gesonderter Vereinbarung. Diese Einwilligung kann für zukünftige Nutzungen widerrufen werden. Bereits veröffentlichte Medien bleiben hiervon unberührt, soweit gesetzlich zulässig.";

function ageOf(value:string){if(!value)return null;const b=new Date(value+"T00:00:00"),t=new Date();let a=t.getFullYear()-b.getFullYear();if(t.getMonth()<b.getMonth()||(t.getMonth()===b.getMonth()&&t.getDate()<b.getDate()))a--;return a}

function Signature({label,onChange}:{label:string,onChange:(s:string)=>void}){
 const ref=useRef<HTMLCanvasElement>(null),drawing=useRef(false);const [signed,setSigned]=useState(false);
 const pos=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*e.currentTarget.width/r.width,y:(e.clientY-r.top)*e.currentTarget.height/r.height}};
 const start=(e:React.PointerEvent<HTMLCanvasElement>)=>{e.currentTarget.setPointerCapture(e.pointerId);const c=e.currentTarget.getContext("2d"),p=pos(e);drawing.current=true;if(c){c.lineCap="round";c.lineJoin="round";c.lineWidth=4;c.strokeStyle="#17211d";c.beginPath();c.moveTo(p.x,p.y)}};
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const c=e.currentTarget.getContext("2d"),p=pos(e);c?.lineTo(p.x,p.y);c?.stroke();setSigned(true)};
 const end=()=>{if(!drawing.current)return;drawing.current=false;onChange(ref.current?.toDataURL()||"")};
 const clear=()=>{const c=ref.current;c?.getContext("2d")?.clearRect(0,0,c.width,c.height);setSigned(false);onChange("")};
 return <div><div className="sig-head"><label>{label} *</label>{signed&&<button type="button" onClick={clear}>Löschen</button>}</div><canvas ref={ref} width="800" height="260" aria-label={`${label} unterschreiben`} onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end}/><small>Mit Finger oder Stift unterschreiben</small></div>
}

async function logoData(){const b=await(await fetch("./chris-franz-design-logo.png")).blob();return await new Promise<string>(r=>{const f=new FileReader();f.onloadend=()=>r(String(f.result));f.readAsDataURL(b)})}

export default function Home(){
 const [f,setF]=useState({name:"",street:"",city:"",birth:"",birthText:"",email:"",insta:"",guardian:"",guardianEmail:"",consent:false});
 const [modelSig,setModelSig]=useState(""),[photoSig,setPhotoSig]=useState(""),[guardianSig,setGuardianSig]=useState(""),[status,setStatus]=useState("");
 const age=useMemo(()=>ageOf(f.birth),[f.birth]),minor=age!==null&&age<18,future=age!==null&&age<0,today=new Date().toISOString().slice(0,10);
 const emailOk=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.email.trim()),guardianEmailOk=!minor||/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(f.guardianEmail.trim());
 const missing=[!f.name.trim()&&"Name",!f.street.trim()&&"Anschrift",!f.city.trim()&&"PLZ und Ort",(!f.birth||future)&&"gültiges Geburtsdatum",!emailOk&&"gültige E-Mail-Adresse",!f.consent&&"Zustimmung",!modelSig&&"Unterschrift des Models",!photoSig&&"Unterschrift des Fotografen",minor&&!f.guardian.trim()&&"Name der erziehungsberechtigten Person",minor&&!guardianEmailOk&&"E-Mail der erziehungsberechtigten Person",minor&&!guardianSig&&"Unterschrift der erziehungsberechtigten Person"].filter((item):item is string=>Boolean(item));
 const ready=missing.length===0;
 const update=(e:React.ChangeEvent<HTMLInputElement>)=>setF(v=>({...v,[e.target.name]:e.target.type==="checkbox"?e.target.checked:e.target.value}));
 const updateBirthText=(e:React.ChangeEvent<HTMLInputElement>)=>{const digits=e.target.value.replace(/\D/g,"").slice(0,8),formatted=digits.length<=2?digits:digits.length<=4?`${digits.slice(0,2)}.${digits.slice(2)}`:`${digits.slice(0,2)}.${digits.slice(2,4)}.${digits.slice(4)}`;let iso="";if(digits.length===8){const day=Number(digits.slice(0,2)),month=Number(digits.slice(2,4)),year=Number(digits.slice(4)),date=new Date(year,month-1,day);if(year>=1900&&date.getFullYear()===year&&date.getMonth()===month-1&&date.getDate()===day)iso=`${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`}setF(v=>({...v,birthText:formatted,birth:iso}))};
 const updateBirthCalendar=(e:React.ChangeEvent<HTMLInputElement>)=>{const value=e.target.value,parts=value.split("-");setF(v=>({...v,birth:value,birthText:value&&parts.length===3?`${parts[2]}.${parts[1]}.${parts[0]}`:""}))};
 const makePdf=async()=>{setStatus("PDF wird erstellt …");const p=new jsPDF({unit:"mm",format:"a4"}),m=16,w=178,logo=await logoData();p.setTextColor(24,34,30);p.addImage(logo,"PNG",m,9,35,35);p.setFont("helvetica","bold");p.setFontSize(20);p.text("MODEL-RELEASE",56,21);p.setFontSize(10);p.setFont("helvetica","normal");p.text("Einwilligung zur Veröffentlichung von Fotoaufnahmen",56,28);p.setDrawColor(179,145,79);p.line(m,47,194,47);p.setFont("helvetica","bold");p.text("FOTOGRAF",m,55);p.setFont("helvetica","normal");p.setFontSize(9);p.text(["Chris Franz Design · Christopher Franz","Schlesische Straße 15 · 31008 Elze","design@chris-franz.de"],m,61);p.setFont("helvetica","bold");p.text("MODEL",112,55);p.setFont("helvetica","normal");p.text([f.name,`${f.street} · ${f.city}`,`Geburtsdatum: ${new Date(f.birth+"T00:00:00").toLocaleDateString("de-DE")}`,f.email,f.insta?`Instagram: ${f.insta}`:""].filter(Boolean),112,61);p.setFont("helvetica","bold");p.text("EINWILLIGUNG",m,91);p.setFont("helvetica","normal");p.setFontSize(9.3);const lines=p.splitTextToSize(consentText.replace("Chris Franz Design","CHRIS FRANZ DESIGN"),w);p.text(lines,m,98,{lineHeightFactor:1.38});let y=98+lines.length*4.1+5;if(minor){p.setFillColor(245,242,234);p.roundedRect(m,y,w,19,2,2,"F");p.setFont("helvetica","bold");p.text("ERZIEHUNGSBERECHTIGTE PERSON",m+4,y+6);p.setFont("helvetica","normal");p.text(`${f.guardian} · ${f.guardianEmail}`,m+4,y+12);y+=25}p.setFontSize(8.5);p.text(`Abgeschlossen am ${new Date().toLocaleDateString("de-DE")}`,m,y);y+=7;const sw=minor?54:80,g=minor?8:18,sigs=[{i:modelSig,l:"Unterschrift Model"},...(minor?[{i:guardianSig,l:"Erziehungsberechtigte Person"}]:[]),{i:photoSig,l:"Unterschrift Fotograf"}];sigs.forEach((s,n)=>{const x=m+n*(sw+g);p.setDrawColor(220);p.roundedRect(x,y,sw,25,1.5,1.5);p.addImage(s.i,"PNG",x+2,y+1,sw-4,20);p.setFontSize(minor?6.8:8);p.text(s.l,x,y+29)});p.setFontSize(7.4);p.setTextColor(95);p.text("Widerruf für zukünftige Nutzungen: design@chris-franz.de",m,287);const name=`Model-Release_${f.name.trim().replace(/\s+/g,"-")}_${today}.pdf`;p.save(name);setStatus("PDF wurde auf deinem Gerät gespeichert. Du kannst sie jetzt selbst per E-Mail verschicken.")};
 return <main><section className="card"><header><img src="./chris-franz-design-logo.png" alt="Chris Franz Design Logo"/><div><span className="eyebrow">Einwilligung zur Bildnutzung</span><h1>Model-Release</h1><p>Digital ausfüllen, unterschreiben und als PDF sichern.</p></div></header><div className="photographer"><div><span className="eyebrow">Fotograf</span><strong>Chris Franz Design · Christopher Franz</strong></div><address>Schlesische Straße 15 · 31008 Elze<br/><a href="mailto:design@chris-franz.de">design@chris-franz.de</a></address></div>
 <form onSubmit={e=>{e.preventDefault();if(ready)makePdf()}}><fieldset><legend>Daten des Models</legend><div className="grid"><label className="wide">Vor- und Nachname *<input name="name" autoComplete="name" value={f.name} onChange={update} required/></label><label className="wide">Straße und Hausnummer *<input name="street" autoComplete="street-address" value={f.street} onChange={update} required/></label><label>PLZ und Ort *<input name="city" value={f.city} onChange={update} required/></label><label>Geburtsdatum *<div className="birth-control"><input className="birth-text" name="birthText" type="text" inputMode="numeric" autoComplete="bday" placeholder="TT.MM.JJJJ" maxLength={10} value={f.birthText} onChange={updateBirthText} required aria-label="Geburtsdatum als TT.MM.JJJJ eingeben"/><span className="calendar-icon" aria-hidden="true">▦</span><input className="birth-picker" name="birth" type="date" min="1900-01-01" max={today} value={f.birth} onChange={updateBirthCalendar} aria-label="Geburtsdatum über Kalender auswählen"/></div></label><label>E-Mail *<input name="email" type="email" inputMode="email" value={f.email} onChange={update} required/></label><label>Instagram <em>(optional)</em><input name="insta" placeholder="@username" value={f.insta} onChange={update}/></label></div>{f.birth&&!future&&<p className={`age ${minor?"minor":""}`}>{minor?`Minderjährig (${age} Jahre) – Zustimmung erforderlich.`:`Volljährig (${age} Jahre).`}</p>}{future&&<p className="age error">Bitte gültiges Geburtsdatum eingeben.</p>}</fieldset>
 {minor&&<fieldset className="guardian"><legend>Erziehungsberechtigte Person</legend><div className="grid"><label>Name *<input name="guardian" value={f.guardian} onChange={update} required/></label><label>E-Mail *<input name="guardianEmail" type="email" inputMode="email" value={f.guardianEmail} onChange={update} required/></label></div></fieldset>}
 <fieldset><legend>Einwilligung</legend><p className="copy">{consentText.split("Chris Franz Design")[0]}<em className="brand-name">Chris Franz Design</em>{consentText.split("Chris Franz Design")[1]}</p><label className="check"><input name="consent" type="checkbox" checked={f.consent} onChange={update} required/><span>Ich habe die Vereinbarung gelesen und stimme ihr zu. *</span></label></fieldset>
 <fieldset><legend>Unterschriften</legend><div className={`signatures ${minor?"three":""}`}><Signature label="Model" onChange={setModelSig}/>{minor&&<Signature label="Erziehungsberechtigte Person" onChange={setGuardianSig}/>}<Signature label="Fotograf" onChange={setPhotoSig}/></div></fieldset><div className="actions">{!ready&&<div className="missing" role="status"><strong>Noch nicht vollständig</strong><span>Bitte ergänzen: {missing.join(", ")}.</span></div>}<button className="confirm" disabled={!ready} aria-disabled={!ready}>Vereinbarung bestätigen & PDF speichern</button>{status&&<p role="status" className="status">{status}</p>}</div></form><footer>Chris Franz Design · Model-Release · <a href="mailto:design@chris-franz.de">Widerruf für zukünftige Nutzungen</a></footer></section></main>
}
